apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-boot-and-kubernetes
  name: spring-boot-and-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-and-kubernetes
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-boot-and-kubernetes
    spec:
      containers:
      - image: brossierp/spring-boot-and-kubernetes
        name: spring-boot-and-kubernetes
        resources: {}
status: {}
