apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-boot-and-kubernetes
  name: spring-boot-and-kubernetes
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-and-kubernetes
  type: LoadBalancer
status:
  loadBalancer: {}
